name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      target:
        description: 'Target to publish'
        required: true
      tag:
        description: 'image tag'
        required: true

env:
  CI: true

jobs:
  publish:
    name: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: mashulgin
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64
          target: ${{ github.event.inputs.target }}
          tags: ${{ github.event.inputs.tag }}

      - name: Publish
        run: "docker push mashulgin/$TARGET:$TAG"
        env:
          TARGET: ${{ github.event.inputs.target }}
          TAG: ${{ github.event.inputs.tag }}
